const plantData = [
  {
    bloomingSeason: 'Winter / Spring',
    climate: 'Tropical',
    commonName: ['Janet Craig'],
    growth: 'Regular',
    id: '8914972',
    img: 'http://www.tropicopia.com/house-plant/thumbnails/5556.jpg',
    latinName: "Dracaena deremensis 'Janet Craig'",
    leafColors0: 'Dark green',
    lightIdeal: 'Strong light ( 21,500 to 3,200 lux/2000 to 300 fc)',
    lightTolered: 'Diffuse light ( Less than 5,300 lux / 500 fc)',
    pruning: 'If needed',
    temps: {
      max: 86,
      min: 50,
    },
    watering: 'Keep moist between watering & Can dry between watering',
  },
  {
    bloomingSeason: null,
    climate: 'Tropical',
    commonName: [
      'Parlor ivy',
      'Sweetheart plant',
      'Heartleaf philodendron',
      'Cordatum vine',
    ],
    growth: 'Regular',
    id: '8915259',
    img: 'http://www.tropicopia.com/house-plant/thumbnails/5689.jpg',
    latinName: 'Philodendron scandens oxycardium',
    leafColors: ['Dark green'],
    lightIdeal: 'Strong light ( 21,500 to 3,200 lux/2000 to 300 fc)',
    lightTolered: 'Diffuse light ( Less than 5,300 lux / 500 fc)',
    pruning: 'If needed',
    temps: {
      max: 82.4,
      min: 64.4,
    },
    watering: 'Keep moist between watering & Water when soil is half dry',
  },
  {
    bloomingSeason: 'All year',
    climate: 'Tropical',
    commonName: ['Peace lily'],
    growth: 'Regular',
    id: '8915270',
    img: 'http://www.tropicopia.com/house-plant/thumbnails/5759.jpg',
    latinName: "Spathiphyllum 'Domino'",
    leafColors: ['Dark green', 'White'],
    lightIdeal: 'Strong light ( 21,500 to 3,200 lux/2000 to 300 fc)',
    lightTolered: 'Diffuse light ( Less than 5,300 lux / 500 fc)',
    pruning: 'Never',
    temps: {
      max: 82.4,
      min: 59,
    },
    watering: 'Keep moist between watering & Must not dry between watering',
  },
  {
    bloomingSeason: null,
    climate: 'Tropical humid',
    commonName: ['Miniature treefern', 'Dwarf treefern'],
    growth: 'Regular',
    id: '8915289',
    img: 'http://www.tropicopia.com/house-plant/thumbnails/5500.jpg',
    latinName: 'Blechnum gibbum',
    leafColors: ['Light green'],
    lightIdeal: 'Strong light ( 21,500 to 3,200 lux/2000 to 300 fc)',
    lightTolered: 'Diffuse light ( Less than 5,300 lux / 500 fc)',
    pruning: 'Never',
    temps: {
      max: 86,
      min: 50,
    },
    watering: 'Keep moist between watering & Must not dry between watering',
  },
];

export default plantData;
