export default [
  {
    id: '10739100',
    images: ['https://i.imgur.com/V7qUyTy.png'],
    isPosted: true,
    poster: 'akbarimo',
  },
  {
    id: '10739101',
    images: ['https://i.imgur.com/V7qUyTy.png'],
    isPosted: true,
    poster: 'akbarimo',
  },
  {
    id: '10739102',
    images: ['https://i.imgur.com/V7qUyTy.png'],
    isPosted: true,
    poster: 'akbarimo',
  },
  {
    id: '10739103',
    images: ['https://i.imgur.com/V7qUyTy.png'],
    isPosted: true,
    poster: 'akbarimo',
  },
  {
    id: '10739104',
    images: ['https://i.imgur.com/V7qUyTy.png'],
    isPosted: true,
    poster: 'akbarimo',
  },
  {
    id: '10739105',
    images: ['https://i.imgur.com/V7qUyTy.png'],
    isPosted: true,
    poster: 'akbarimo',
  },
  {
    id: '10739106',
    images: ['https://i.imgur.com/V7qUyTy.png'],
    isPosted: true,
    poster: 'akbarimo',
  },
  {
    id: '10739107',
    images: ['https://i.imgur.com/V7qUyTy.png'],
    isPosted: true,
    poster: 'akbarimo',
  },
  {
    id: '10739108',
    images: ['https://i.imgur.com/V7qUyTy.png'],
    isPosted: true,
    poster: 'akbarimo',
  },
  {
    id: '10739109',
    images: ['https://i.imgur.com/V7qUyTy.png'],
    isPosted: true,
    poster: 'akbarimo',
  },
  {
    id: '10739110',
    images: ['https://i.imgur.com/V7qUyTy.png'],
    isPosted: true,
    poster: 'akbarimo',
  },
  {
    id: '10739111',
    images: ['https://i.imgur.com/V7qUyTy.png'],
    isPosted: true,
    poster: 'akbarimo',
  },
  {
    id: '10739112',
    images: ['https://i.imgur.com/V7qUyTy.png'],
    isPosted: true,
    poster: 'akbarimo',
  },
  {
    id: '10739113',
    images: ['https://i.imgur.com/V7qUyTy.png'],
    isPosted: true,
    poster: 'akbarimo',
  },
  {
    id: '10739114',
    images: ['https://i.imgur.com/V7qUyTy.png'],
    isPosted: true,
    poster: 'akbarimo',
  },
  {
    id: '10739115',
    images: ['https://i.imgur.com/V7qUyTy.png'],
    isPosted: true,
    poster: 'akbarimo',
  },
  {
    id: '10739116',
    images: ['https://i.imgur.com/V7qUyTy.png'],
    isPosted: true,
    poster: 'akbarimo',
  },
  {
    id: '10739170',
    images: ['https://i.imgur.com/V7qUyTy.png'],
    isPosted: true,
    poster: 'akbarimo',
  },
  {
    id: '10739118',
    images: ['https://i.imgur.com/V7qUyTy.png'],
    isPosted: true,
    poster: 'akbarimo',
  },
  {
    id: '10739119',
    images: ['https://i.imgur.com/V7qUyTy.png'],
    isPosted: true,
    poster: 'akbarimo',
  },
  {
    id: '10739120',
    images: ['https://i.imgur.com/V7qUyTy.png'],
    isPosted: true,
    poster: 'akbarimo',
  },
  {
    id: '10739121',
    images: ['https://i.imgur.com/V7qUyTy.png'],
    isPosted: true,
    poster: 'akbarimo',
  },
];
